
-- plan_site_conditions: soil/terrain data per obra
CREATE TABLE public.plan_site_conditions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  obra_id uuid REFERENCES public.obras(id) ON DELETE CASCADE NOT NULL,
  user_id uuid NOT NULL,
  tipo_solo text NOT NULL DEFAULT 'misto',
  capacidade_portante_kpa numeric DEFAULT 150,
  nivel_freatico_m numeric DEFAULT 3.0,
  zona_sismica text DEFAULT 'B',
  topografia text DEFAULT 'plano',
  area_implantacao_m2 numeric DEFAULT 0,
  numero_pisos integer DEFAULT 1,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(obra_id)
);

ALTER TABLE public.plan_site_conditions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view site conditions"
  ON public.plan_site_conditions FOR SELECT TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

CREATE POLICY "Authenticated users can insert site conditions"
  ON public.plan_site_conditions FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owners can update site conditions"
  ON public.plan_site_conditions FOR UPDATE TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

CREATE POLICY "Owners can delete site conditions"
  ON public.plan_site_conditions FOR DELETE TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

-- plan_infra_scenarios: foundation scenarios generated by Axia
CREATE TABLE public.plan_infra_scenarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_condition_id uuid REFERENCES public.plan_site_conditions(id) ON DELETE CASCADE NOT NULL,
  user_id uuid NOT NULL,
  nome text NOT NULL,
  tipo_fundacao text NOT NULL DEFAULT 'sapatas_isoladas',
  descricao text,
  parametros jsonb DEFAULT '{}'::jsonb,
  custo_estimado numeric DEFAULT 0,
  selecionado boolean DEFAULT false,
  axia_confidence numeric DEFAULT 0,
  axia_reasoning text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.plan_infra_scenarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view infra scenarios"
  ON public.plan_infra_scenarios FOR SELECT TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

CREATE POLICY "Authenticated users can insert infra scenarios"
  ON public.plan_infra_scenarios FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owners can update infra scenarios"
  ON public.plan_infra_scenarios FOR UPDATE TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

CREATE POLICY "Owners can delete infra scenarios"
  ON public.plan_infra_scenarios FOR DELETE TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

-- plan_infra_items: parametric items within a selected scenario
CREATE TABLE public.plan_infra_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id uuid REFERENCES public.plan_infra_scenarios(id) ON DELETE CASCADE NOT NULL,
  artigo_base_id uuid,
  descricao text NOT NULL,
  unidade text NOT NULL DEFAULT 'm2',
  quantidade numeric NOT NULL DEFAULT 0,
  preco_unitario numeric NOT NULL DEFAULT 0,
  valor_total numeric NOT NULL DEFAULT 0,
  formula_origem text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.plan_infra_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view infra items"
  ON public.plan_infra_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.plan_infra_scenarios s
      WHERE s.id = plan_infra_items.scenario_id
        AND s.user_id = ANY(public.get_org_member_ids())
    )
  );

CREATE POLICY "Authenticated users can insert infra items"
  ON public.plan_infra_items FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.plan_infra_scenarios s
      WHERE s.id = plan_infra_items.scenario_id
        AND s.user_id = ANY(public.get_org_member_ids())
    )
  );

CREATE POLICY "Owners can update infra items"
  ON public.plan_infra_items FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.plan_infra_scenarios s
      WHERE s.id = plan_infra_items.scenario_id
        AND s.user_id = ANY(public.get_org_member_ids())
    )
  );

CREATE POLICY "Owners can delete infra items"
  ON public.plan_infra_items FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.plan_infra_scenarios s
      WHERE s.id = plan_infra_items.scenario_id
        AND s.user_id = ANY(public.get_org_member_ids())
    )
  );

-- plan_infra_budget_links: link infra items to budget articles
CREATE TABLE public.plan_infra_budget_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  infra_item_id uuid REFERENCES public.plan_infra_items(id) ON DELETE CASCADE NOT NULL,
  user_id uuid NOT NULL,
  orcamento_id uuid REFERENCES public.orcamentos(id) ON DELETE CASCADE NOT NULL,
  artigo_orcamento_id uuid REFERENCES public.artigos_orcamento(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.plan_infra_budget_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view infra budget links"
  ON public.plan_infra_budget_links FOR SELECT TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));

CREATE POLICY "Authenticated users can insert infra budget links"
  ON public.plan_infra_budget_links FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owners can delete infra budget links"
  ON public.plan_infra_budget_links FOR DELETE TO authenticated
  USING (user_id = ANY(public.get_org_member_ids()));
