
-- Adicionar novos campos ao supplier_profiles para cadastro completo
ALTER TABLE public.supplier_profiles
  ADD COLUMN IF NOT EXISTS responsavel_nome text,
  ADD COLUMN IF NOT EXISTS telemovel text,
  ADD COLUMN IF NOT EXISTS morada_completa text,
  ADD COLUMN IF NOT EXISTS codigo_postal text,
  ADD COLUMN IF NOT EXISTS localidade text,
  ADD COLUMN IF NOT EXISTS pais text DEFAULT 'Portugal',
  ADD COLUMN IF NOT EXISTS cae_principal text,
  ADD COLUMN IF NOT EXISTS cae_secundario text,
  ADD COLUMN IF NOT EXISTS telefone_fixo text,
  ADD COLUMN IF NOT EXISTS email_comercial text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS ano_fundacao integer,
  ADD COLUMN IF NOT EXISTS num_colaboradores text,
  ADD COLUMN IF NOT EXISTS certificacoes text[],
  ADD COLUMN IF NOT EXISTS categoria_principal text,
  ADD COLUMN IF NOT EXISTS subcategorias text[],
  ADD COLUMN IF NOT EXISTS zona_atuacao text DEFAULT 'nacional',
  ADD COLUMN IF NOT EXISTS distritos_atuacao text[],
  ADD COLUMN IF NOT EXISTS raio_atuacao_km integer,
  ADD COLUMN IF NOT EXISTS tipo_fornecimento text[],
  ADD COLUMN IF NOT EXISTS prazo_medio_entrega text,
  ADD COLUMN IF NOT EXISTS trabalha_credito boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS prazo_pagamento_padrao text,
  ADD COLUMN IF NOT EXISTS desconto_volume boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS aceita_pedidos_plataforma boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS permite_api boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS atualizacao_precos text DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS frequencia_atualizacao text,
  ADD COLUMN IF NOT EXISTS aceita_termos boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS aceita_comunicacoes boolean DEFAULT false;
