
TRUNCATE TABLE public.matriz_capitulos_padrao;

INSERT INTO public.matriz_capitulos_padrao (codigo, ordem, titulo) VALUES
  ('00',   0,  'Requisitos Gerais'),
  ('01.a', 1,  'Trabalhos Preparatórios e Implantação'),
  ('01.b', 2,  'Estaleiro'),
  ('02',   3,  'Demolições e Desmontagens'),
  ('03',   4,  'Movimentos de Terras'),
  ('04',   5,  'Fundações Especiais / Contenções'),
  ('05',   6,  'Estrutura Betão Armado'),
  ('06',   7,  'Estruturas Metálicas'),
  ('07',   8,  'Estruturas de Madeira'),
  ('08',   9,  'Pavimento Térreo'),
  ('09',   10, 'Drenagens, Impermeabilizações e Isolamentos (fase tosco)'),
  ('010',  11, 'Alvenarias / Paredes Secas'),
  ('011',  12, 'Cobertura'),
  ('012',  13, 'Impermeabilizações e Isolamentos (fase acabamentos)'),
  ('013',  14, 'Cantarias'),
  ('014',  15, 'Revestimentos Pavimentos'),
  ('015',  16, 'Revestimentos Paredes'),
  ('016',  17, 'Revestimentos Tectos'),
  ('017',  18, 'Caixilharias Exteriores'),
  ('018',  19, 'Proteção Solar'),
  ('019',  20, 'Serralharias'),
  ('020',  21, 'Carpintarias'),
  ('021',  22, 'Pinturas'),
  ('022',  23, 'Instalações Hidráulicas'),
  ('023',  24, 'Rede Interna de Distribuição de Gás'),
  ('024',  25, 'Segurança Contra Incêndios (SCI)'),
  ('025',  26, 'Aspiração Central'),
  ('026',  27, 'Instalações Mecânicas'),
  ('027',  28, 'Elevadores'),
  ('028',  29, 'Equipamentos Sanitários'),
  ('029',  30, 'Instalações Eléctricas'),
  ('030',  31, 'Infraestruturas de Telecomunicações (ITED)'),
  ('031',  32, 'Sistema Alarme + CCTV'),
  ('032',  33, 'Automação / Domótica'),
  ('033',  34, 'Painéis Solares'),
  ('034',  35, 'Cozinhas'),
  ('035',  36, 'Arranjos Exteriores'),
  ('036',  37, 'Limpezas e Trabalhos de Acabamentos Finais');
